### ISSUE TITLE
Would it be possible not to depend on Ruby?

### ISSUE THREAD

**Issue by guidomb** [Wolox/frontend-bootstrap#29]
I know this is not a big issue but it would be nice not to depend on Ruby. Currently we rely on Ruby gems beings installed in order to install scss_lint. Is there any way to install scss_lint using an npm package?

**Comment by sbalay** [comment]
I know this would be a nice feature.
Doing some research I found this linter https://github.com/sasstools/sass-lint . Its development restarted few weeks ago and now it seems production ready. It relies on node sass rather than ruby sass and already has a gulp plugin.
@SKOLZ can you check if it can replace the current linter we have?

Thanks @guidomb for reporting the issue

**Comment by sbalay** [comment]
@SKOLZ another linter https://github.com/stylelint/stylelint

**Comment by sbalay** [comment]
#49
